plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.3'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.protobuf' version '0.9.5'
}

group = 'com.playtab'
version = '0.0.1-SNAPSHOT'
description = 'lineupservice'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

ext {
	grpcVersion = '1.76.0'
	protobufVersion = '4.33.1'
	grpcSpringBootStarterVersion = '3.1.0.RELEASE'
}

dependencies {
	// gRPC Server (Spring Boot)
	implementation 'net.devh:grpc-server-spring-boot-starter:3.1.0.RELEASE'

	// Protobuf / gRPC
	implementation platform("io.grpc:grpc-bom:1.66.0")
	implementation 'io.grpc:grpc-protobuf'
	implementation 'io.grpc:grpc-stub'
	implementation 'io.grpc:grpc-netty-shaded'

	// DB
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.flywaydb:flyway-core'
	runtimeOnly 'org.postgresql:postgresql'

	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation "com.google.protobuf:protobuf-java-util:3.25.3"

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	compileOnly 'org.apache.tomcat:annotations-api:6.0.53'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation "io.grpc:grpc-testing"
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

protobuf {
	protoc {
		artifact = "com.google.protobuf:protoc:3.25.5"
	}
	plugins {
		grpc {
			artifact = "io.grpc:protoc-gen-grpc-java:1.66.0"
		}
	}
	generateProtoTasks {
		all().configureEach {
			plugins {
				grpc {}
			}
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}