spring:
  application:
    name: lineup-service


  datasource:
    url: ${DB:URL}
    username: ${DB:USERNAME}
    password: ${DB:PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

grpc:
  server:
    port: ${GRPC_PORT:9091}
    reflection-service-enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    net.devh.boot.grpc: info
